### ISSUE TITLE
Are there a Linux version?

### ISSUE THREAD

**Issue by imalightbulb** [sohalsdr/mdMathTool#1]
I'm in arch linux and want to use this tool. 
But when I try to run this file I got this:
![image](https://user-images.githubusercontent.com/66677431/97711794-8164a380-1af8-11eb-9949-6dcbb5eddbf9.png)
Looking forward to try this program, thanks.

**Comment by sohalsdr** [comment]
Interesting, I just tested the latest release on my arch system and have had no issues, please try it without the `-m` argument, I'm able to run it with the standard `java -jar mdmathtool_1.2.0.jar`.

**Comment by sohalsdr** [comment]
I also hope to create an AUR package once I understand a little more about how AUR works, I haven't used Arch until recently.

**Comment by imalightbulb** [comment]
It says `No Mode argument found, please run with a mode argument`
(Btw I've switched to openSUSE tumbleweed)

**Comment by sohalsdr** [comment]
That's intended behavior, the mode arguments are explained in the readme, and if you run it with the "help" argument.
